// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Happy path - smoke tests', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Correct login and check user name on header', async function() {
    await driver.get("http://127.0.0.1:5173/home")
    await driver.manage().window().setRect({ width: 1368, height: 802 })
    await driver.findElement(By.css(".\\_btn_vgjs1_115:nth-child(1) > span")).click()
    await driver.findElement(By.name("email")).click()
    await driver.findElement(By.name("email")).sendKeys("user@email.com")
    await driver.findElement(By.name("password")).sendKeys("password")
    await driver.findElement(By.name("password")).click()
    await driver.findElement(By.css(".\\_form_Container_1s4b4_33")).click()
    await driver.findElement(By.css(".\\_btn_1s4b4_61")).click()
    {
      const elements = await driver.findElements(By.xpath("//h2[contains(.,\'Hola Equipo #4\')]"))
      assert(elements.length)
    }
    await driver.close()
  })
  it('Search cars by category SUV and check category SUV in card', async function() {
    await driver.get("http://127.0.0.1:5173/home")
    await driver.manage().window().setRect({ width: 1368, height: 802 })
    await driver.findElement(By.xpath("//img[contains(@src,\'https://totalrenting.es/wp-content/uploads/2022/06/1711-X8-1.jpg\')]")).click()
    {
      const elements = await driver.findElements(By.xpath("//span[contains(.,\'SUV\')]"))
      assert(elements.length)
    }
    await driver.close()
  })
  it('Search cars by city Medellin and check h2 contain Medellin in card', async function() {
    await driver.get("http://127.0.0.1:5173/home")
    await driver.manage().window().setRect({ width: 1368, height: 802 })
    await driver.findElement(By.id("cities")).click()
    {
      const dropdown = await driver.findElement(By.id("cities"))
      await dropdown.findElement(By.xpath("//option[. = 'Medellin']")).click()
    }
    await driver.findElement(By.id("from")).click()
    await driver.findElement(By.id("from")).sendKeys("2024-01-10")
    await driver.findElement(By.id("until")).click()
    await driver.findElement(By.id("until")).sendKeys("2024-01-17")
    await driver.findElement(By.css(".\\_search_icon_11vu1_181 > path")).click()
    {
      const elements = await driver.findElements(By.xpath("//h3[contains(.,\'Medellin\')]"))
      assert(elements.length)
    }
    await driver.close()
  })
  it('Correct display features from a random car detail page', async function() {
    await driver.get("http://127.0.0.1:5173/home")
    await driver.manage().window().setRect({ width: 1368, height: 802 })
    await driver.executeScript("window.scrollTo(0,777.5999755859375)")
    await driver.findElement(By.linkText("Details")).click()
    {
      const elements = await driver.findElements(By.css("ol > li:nth-child(1)"))
      assert(elements.length)
    }
    await driver.close()
  })
  it('Correct display policy from a specific random car at card detail page', async function() {
    await driver.get("http://127.0.0.1:5173/home")
    await driver.manage().window().setRect({ width: 1368, height: 802 })
    await driver.findElement(By.linkText("Details")).click()
    await driver.executeScript("window.scrollTo(0,785.5999755859375)")
    {
      const elements = await driver.findElements(By.xpath("//h4[contains(.,\'Cancelation politics\')]"))
      assert(elements.length)
    }
  })
})
