// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Spring 3 test suite', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Correct checking to access booking only if user is logged', async function() {
    await driver.get("http://127.0.0.1:5173/home")
    await driver.manage().window().setRect({ width: 1372, height: 806 })
    await driver.findElement(By.linkText("Details")).click()
    await driver.executeScript("window.scrollTo(0,292.79998779296875)")
    await driver.findElement(By.css(".\\_cont_reserve_calendar_yydp6_263 > button")).click()
    await driver.findElement(By.name("email")).click()
    await driver.findElement(By.name("email")).sendKeys("test2@gmail.com")
    await driver.findElement(By.name("password")).click()
    await driver.findElement(By.name("password")).sendKeys("Contraseña123")
    await driver.findElement(By.css(".\\_btn_container_1s4b4_109")).click()
    await driver.findElement(By.css(".\\_btn_1s4b4_61")).click()
    await driver.findElement(By.linkText("Details")).click()
    await driver.executeScript("window.scrollTo(0,292.79998779296875)")
    await driver.findElement(By.css(".\\_cont_reserve_calendar_yydp6_263 > button")).click()
    await driver.executeScript("window.scrollTo(0,900)")
    await driver.findElement(By.css(".\\_first_grid_area_1da5g_485 > .\\_title_booking_1da5g_67")).click()
    {
      const elements = await driver.findElements(By.css(".\\_first_grid_area_1da5g_485 > .\\_title_booking_1da5g_67"))
      assert(elements.length)
    }
    await driver.findElement(By.linkText("Logout")).click()
    await driver.close()
  })
  it('Correct user login', async function() {
    await driver.get("http://127.0.0.1:5173/home")
    await driver.manage().window().setRect({ width: 1372, height: 806 })
    await driver.findElement(By.css(".\\_btn_vgjs1_115:nth-child(1) > span")).click()
    await driver.findElement(By.name("email")).click()
    await driver.findElement(By.name("email")).sendKeys("test2@gmail.com")
    await driver.findElement(By.name("password")).sendKeys("Contraseña123")
    await driver.findElement(By.css(".\\_btn_1s4b4_61")).click()
    {
      const elements = await driver.findElements(By.xpath("//h2[contains(.,\'Hola Equipo #4\')]"))
      assert(elements.length)
    }
    await driver.close()
  })
})
